"""empty message

Revision ID: 1b118fc30ef7
Revises: 
Create Date: 2019-07-23 17:18:09.706605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b118fc30ef7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tools_machine_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_area', sa.String(length=64), nullable=True),
    sa.Column('tool_id', sa.String(length=64), nullable=True),
    sa.Column('host_name', sa.String(length=64), nullable=True),
    sa.Column('os', sa.String(length=64), nullable=True),
    sa.Column('av', sa.String(length=64), nullable=True),
    sa.Column('usb', sa.String(length=64), nullable=True),
    sa.Column('dvd', sa.String(length=64), nullable=True),
    sa.Column('floppy', sa.String(length=64), nullable=True),
    sa.Column('vnc', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('ams', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tools_machine_test')
    # ### end Alembic commands ###
