"""update tool_info

Revision ID: 202aa38ba681
Revises: 1b118fc30ef7
Create Date: 2019-07-26 23:39:36.617989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202aa38ba681'
down_revision = '1b118fc30ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools_machine_test', sa.Column('remark', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools_machine_test', 'remark')
    # ### end Alembic commands ###
